source "https://rubygems.org"

gem "rails", "~> 7.2.0"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.7"
gem "rack-cors"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[windows jruby]

# Background Jobs
gem "sidekiq", "~> 7.0"
gem "sidekiq-cron", "~> 1.12"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "factory_bot_rails"
  gem "shoulda-matchers", "~> 5.0"
  gem "database_cleaner-active_record"
  gem "faker"
end

group :development do
  gem "brakeman", require: false
end

group :test do
  gem "minitest-reporters"
  gem "simplecov", require: false
end
